name = "SpiDy"
uuid = "a4849050-cccd-45e7-a409-2b114d5ccb2f"
authors = ["Stefano Scali <scali.stefano@gmail.com>", "Federico Cerisola <federico@cerisola.net>"]
version = "1.2.1"

[deps]
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PolynomialRoots = "3a141323-8675-5d76-9d11-e1df1406c778"
PreallocationTools = "d236fae5-4411-538c-8e31-a6e3d9e00b46"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SpectralDensities = "6f27643f-8ff7-45b5-8e20-15c87f132b4c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DifferentialEquations = "7"
Distributions = "0.25"
FFTW = "1"
Interpolations = "0.14, 0.15"
PolynomialRoots = "1"
PreallocationTools = "0.4"
QuadGK = "2"
SpectralDensities = "0.2"
Statistics = "1"
julia = "1.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
